// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB804DD_-2_EjaPdf_WXRlUxauj2MVFFAk',
    appId: '1:250494722355:web:04c5bef80587ae51a51e46',
    messagingSenderId: '250494722355',
    projectId: 'userprofile-c3637',
    authDomain: 'userprofile-c3637.firebaseapp.com',
    storageBucket: 'userprofile-c3637.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrjH2DDP66St8IuInQWMBgCh4x-Q-PQE',
    appId: '1:250494722355:android:27d4bcf6dee44257a51e46',
    messagingSenderId: '250494722355',
    projectId: 'userprofile-c3637',
    storageBucket: 'userprofile-c3637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzHbt4ULqdnVKV8I8UHL2Orux9CeYqUE',
    appId: '1:250494722355:ios:4bd51bc4ef2c8c0da51e46',
    messagingSenderId: '250494722355',
    projectId: 'userprofile-c3637',
    storageBucket: 'userprofile-c3637.appspot.com',
    iosClientId: '250494722355-7cj4ukif89hu6nm969o4sbqr7fs466fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFzHbt4ULqdnVKV8I8UHL2Orux9CeYqUE',
    appId: '1:250494722355:ios:4bd51bc4ef2c8c0da51e46',
    messagingSenderId: '250494722355',
    projectId: 'userprofile-c3637',
    storageBucket: 'userprofile-c3637.appspot.com',
    iosClientId: '250494722355-7cj4ukif89hu6nm969o4sbqr7fs466fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseapp',
  );
}
